server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    #fals表示不用想注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #注册中心互相注册，相互守望
      defaultZone: http://eureka7001.com:7001/eureka
