server:
  port: 8001
spring:
  application:
    name: consul-providor-server
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      port: 8500
      host: localhost