server:
  port: 8001
spring:
  application:
    name: hystrix-payment-server
eureka:
  client:
    register-with-eureka: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: PaymentHystix8001
    prefer-ip-address: true
